"""Data objects representing an agent-maintained todo scratchpad."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

TODO_STATUSES = frozenset({"pending", "in_progress", "completed"})


@dataclass(frozen=True)
class TodoItem:
    """One ordered task in a todo list.

    IDs are assigned by :class:`TodoWriteTool`, rather than generated by the
    model, so a model can safely round-trip an item while updating its status.
    """

    id: str
    content: str
    status: str

    def __post_init__(self) -> None:
        if not isinstance(self.id, str) or not self.id.strip():
            raise ValueError("todo item id must be a non-empty string")
        if not isinstance(self.content, str) or not self.content.strip():
            raise ValueError("todo item content must be a non-empty string")
        if self.status not in TODO_STATUSES:
            raise ValueError(f"todo item status must be one of {sorted(TODO_STATUSES)}")

    def to_dict(self) -> dict[str, str]:
        """Return a JSON-serialisable representation of this item."""
        return {"id": self.id, "content": self.content, "status": self.status}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "TodoItem":
        """Parse a validated todo item from persisted JSON data."""
        if not isinstance(data, dict):
            raise ValueError("todo item must be a dict")
        item_id = data.get("id")
        content = data.get("content")
        status = data.get("status")
        if not isinstance(item_id, str) or not item_id.strip():
            raise ValueError("todo item id must be a non-empty string")
        if not isinstance(content, str) or not content.strip():
            raise ValueError("todo item content must be a non-empty string")
        if not isinstance(status, str) or status not in TODO_STATUSES:
            raise ValueError(f"todo item status must be one of {sorted(TODO_STATUSES)}")
        return cls(item_id, content, status)


@dataclass
class TodoList:
    """The complete ordered todo scratchpad for one agent session."""

    items: list[TodoItem] = field(default_factory=list)

    def to_dict(self) -> dict[str, list[dict[str, str]]]:
        """Return a JSON-serialisable representation of this list."""
        return {"items": [item.to_dict() for item in self.items]}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "TodoList":
        """Parse a validated todo list from persisted JSON data."""
        if not isinstance(data, dict):
            raise ValueError("todo list must be a dict")
        items = data.get("items")
        if not isinstance(items, list):
            raise ValueError("todo list items must be a list")
        parsed = [TodoItem.from_dict(item) for item in items if isinstance(item, dict)]
        if len(parsed) != len(items):
            raise ValueError("each todo item must be a dict")
        return cls(parsed)
